name = "photo-banast-as"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "photo-banast-as"
database_id = "0e1e0261-0f26-42f9-b5f1-333fb94e8eb1"

# Cloudflare R2 Storage binding
[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "photo-banast-as"
